from typing import Any

FILTER_PRESETS: list[dict[str, Any]] = [
    {
        "name": "PostMigration_Expansion",
        "description": "Рост после миграции в DEX при умеренном риске концентрации.",
        "params": {
            "age_min_minutes": 20,
            "age_max_minutes": 240,
            "mc_min_usd": 20000,
            "mc_max_usd": 250000,
            "liq_min_usd": 15000,
            "liq_max_usd": 80000,
            "volume_5m_min_usd": 20000,
            "volume_5m_max_usd": None,
            "trades_5m_min": 20,
            "makers_5m_min": 80,
            "holders_min": 300,
            "holders_max": None,
            "top10_share_max": 0.70,
            "dev_share_max": 0.50,
        },
    },
    {
        "name": "Early_LowCap",
        "description": "Ранний low-cap сценарий с более мягкими требованиями.",
        "params": {
            "age_min_minutes": 10,
            "age_max_minutes": 120,
            "mc_min_usd": 10000,
            "mc_max_usd": 100000,
            "liq_min_usd": 8000,
            "liq_max_usd": 50000,
            "volume_5m_min_usd": 8000,
            "volume_5m_max_usd": None,
            "trades_5m_min": 12,
            "makers_5m_min": 35,
            "holders_min": 120,
            "holders_max": None,
            "top10_share_max": 0.78,
            "dev_share_max": 0.55,
        },
    },
    {
        "name": "Late_Scalp",
        "description": "Короткий скальп на поздней стадии с повышенной ликвидностью.",
        "params": {
            "age_min_minutes": 90,
            "age_max_minutes": 720,
            "mc_min_usd": 50000,
            "mc_max_usd": 700000,
            "liq_min_usd": 30000,
            "liq_max_usd": 200000,
            "volume_5m_min_usd": 30000,
            "volume_5m_max_usd": None,
            "trades_5m_min": 30,
            "makers_5m_min": 100,
            "holders_min": 400,
            "holders_max": None,
            "top10_share_max": 0.68,
            "dev_share_max": 0.45,
        },
    },
]
